apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testt
  name: testt
spec:
  containers:
  - image: nginx
    name: testt
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
